version: '3'
services:
  script:
    build: .
    depends_on:
      - db
    command: tail -f /dev/null

  db:
    image: postgres
    environment:
      POSTGRES_DB: jokes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

